=== genedelisa/rocky-music/rockymusic-core/src/main/resources/chords.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="alias" type="xsd:string"/>
  <xsd:element name="interval" type="xsd:string"/>
  <xsd:element name="chords">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="chord"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="spelling">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="degree"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description" type="xsd:string"/>
  <xsd:element name="degree" type="xsd:string"/>
  <xsd:element name="chord">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element minOccurs="0" ref="aliases"/>
        <xsd:element ref="intervals"/>
        <xsd:element ref="spelling"/>
        <xsd:element minOccurs="0" ref="voicing"/>
        <xsd:element ref="description"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="aliases">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="alias"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="intervals">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="interval"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="voicing">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="degree"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== genedelisa/rocky-music/rockymusic-core/src/main/resources/chorddefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  Rocky Music Core
  %%
  Copyright (C) 1996 - 2014 Rockhopper Technologies
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<!--  chord definitions -->
<!-- Gene De Lisa gene@genedelisa.com -->
<chords xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="chords.xsd">
	<chord name="maj">
		<aliases>
			<alias>Maj</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>7</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
		</spelling>
		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
		</voicing>
		<description>major</description>
	</chord>
	<chord name="m">
		<intervals>
			<interval>3</interval>
			<interval>7</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b3</degree>
			<degree>5</degree>
		</spelling>
		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
		</voicing>
		<description>minor</description>
	</chord>

	<chord name="maj9-5">
		<aliases>
			<alias>maj9b5</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>6</interval>
			<interval>11</interval>
			<interval>14</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>b5</degree>
			<degree>7</degree>
			<degree>9</degree>
		</spelling>
		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>7</degree>
			<degree>9</degree>
		</voicing>
		<description>major ninth diminished fifth</description>
	</chord>
	<chord name="7+9">
		<aliases>
			<alias>7#9</alias>
		</aliases>

		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>15</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>#9</degree>
		</spelling>
		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>7</degree>
			<degree>9</degree>
		</voicing>

		<description>seventh augmented ninth</description>
	</chord>

	<chord name="7+9-13">
		<aliases>
			<alias>7#9b13</alias>
		</aliases>

		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>15</interval>
			<interval>20</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>#9</degree>
			<degree>b13</degree>
		</spelling>
		<description>seventh augmented ninth lowered thirteenth</description>
	</chord>

	<chord name="7+9+11-13">
		<aliases>
			<alias>7#9#11b13</alias>
		</aliases>

		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>15</interval>
			<interval>18</interval>
			<interval>20</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>#9</degree>
			<degree>#11</degree>
			<degree>b13</degree>
		</spelling>
		<description>seventh augmented ninth augmented eleventh lowered thirteenth</description>
	</chord>

	<chord name="13+11-9">
		<aliases>
			<alias>13+11b9</alias>
			<alias>13#11b9</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>13</interval>
			<interval>18</interval>
			<interval>21</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>b9</degree>
			<degree>#11</degree>
			<degree>13</degree>
		</spelling>
		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>7</degree>
			<degree>9</degree>
			<degree>11</degree>
			<degree>13</degree>
		</voicing>
		<description>
			thirteenth augmented eleventh diminished ninth
		</description>
	</chord>
	<chord name="13+11">
		<aliases>
			<alias>13#11</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>18</interval>
			<interval>21</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>#11</degree>
			<degree>13</degree>
		</spelling>
		<description>
			thirteenth augmented eleventh
		</description>
	</chord>
	<chord name="13+5">
		<aliases>
			<alias>13#5</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>8</interval>
			<interval>10</interval>
			<interval>17</interval>
			<interval>21</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>11</degree>
			<degree>13</degree>
		</spelling>
		<description>
			thirteenth augmented eleventh
		</description>
	</chord>
	<chord name="13+5-9">
		<aliases>
			<alias>13#5b9</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>8</interval>
			<interval>10</interval>
			<interval>13</interval>
			<interval>21</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>b9</degree>
			<degree>13</degree>
		</spelling>
		<description>
			thirteenth augmented fifth flat ninth
		</description>
	</chord>
	<chord name="13+5-9+11">
		<aliases>
			<alias>13#5b9#11</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>8</interval>
			<interval>10</interval>
			<interval>13</interval>
			<interval>18</interval>
			<interval>21</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>b9</degree>
			<degree>#11</degree>
			<degree>13</degree>
		</spelling>
		<description>
			thirteenth augmented fifth flat ninth sharp 11
		</description>
	</chord>
	<chord name="13+5+11">
		<aliases>
			<alias>13#5#11</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>8</interval>
			<interval>10</interval>
			<interval>18</interval>
			<interval>21</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>#11</degree>
			<degree>13</degree>
		</spelling>
		<description>
			thirteenth augmented eleventh
		</description>
	</chord>
	<chord name="m11-9">
		<aliases>
			<alias>m11b9</alias>
		</aliases>
		<intervals>
			<interval>3</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>13</interval>
			<interval>17</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>b9</degree>
			<degree>11</degree>
		</spelling>
		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>7</degree>
			<degree>9</degree>
			<degree>11</degree>
		</voicing>
		<description>minor eleventh flat nine</description>
	</chord>
	<chord name="9-5">
		<aliases>
			<alias>9b5</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>6</interval>
			<interval>10</interval>
			<interval>14</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>b5</degree>
			<degree>b7</degree>
			<degree>9</degree>
		</spelling>

		<voicing>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>7</degree>
			<degree>9</degree>
		</voicing>
		<description>ninth diminished fifth</description>
	</chord>
	<chord name="m9-5">
		<aliases>
			<alias>m9b5</alias>
		</aliases>
		<intervals>
			<interval>3</interval>
			<interval>6</interval>
			<interval>10</interval>
			<interval>14</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b3</degree>
			<degree>b5</degree>
			<degree>b7</degree>
			<degree>9</degree>
		</spelling>
		<description>minor ninth diminished fifth</description>
	</chord>
	<chord name="7-9">
		<aliases>
			<alias>7b9</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>13</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>b9</degree>
		</spelling>
		<description>seventh flat 9</description>
	</chord>
	<chord name="7-9-13">
		<aliases>
			<alias>7b9b13</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>13</interval>
			<interval>20</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>b9</degree>
			<degree>b13</degree>
		</spelling>
		<description>seventh flat 9 flat 13</description>
	</chord>
	<chord name="7-9+11">
		<aliases>
			<alias>7b9#11</alias>
		</aliases>
		<intervals>
			<interval>4</interval>
			<interval>7</interval>
			<interval>10</interval>
			<interval>13</interval>
			<interval>18</interval>
		</intervals>
		<spelling>
