=== genedelisa/rocky-music/rockymusic-core/src/main/resources/scaledefs.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="interval" type="xsd:string"/>
  <xsd:element name="descendingIntervals">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="interval"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="scales">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="scale"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="spelling">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="degree"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="scale">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="intervals"/>
        <xsd:element minOccurs="0" ref="descendingIntervals"/>
        <xsd:element minOccurs="0" ref="spelling"/>
        <xsd:element minOccurs="0" ref="description"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="description" type="xsd:string"/>
  <xsd:element name="degree" type="xsd:string"/>
  <xsd:element name="intervals">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="interval"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== genedelisa/rocky-music/rockymusic-core/src/main/resources/scaledefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  Rocky Music Core
  %%
  Copyright (C) 1996 - 2013 Rockhopper Technologies
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<scales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scaledefs.xsd">

	<scale name="Chromatic">
		<intervals>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
		</intervals>
	</scale>
	<scale name="Major">
		<intervals>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>6</degree>
			<degree>7</degree>
		</spelling>
	</scale>
	<scale name="Octatonic">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>4</degree>
			<degree>b5</degree>
			<degree>b6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>

	<scale name="Melodic Minor">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
		</intervals>
		<descendingIntervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
		</descendingIntervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
		<description>different up and down</description>
	</scale>

	<scale name="Harmonic Minor">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>

	<scale name="Japanese">
		<intervals>
			<interval>1</interval>
			<interval>4</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>4</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b2</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Hawaiian">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Bebop minor">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>6</degree>
			<degree>b7</degree>
			<degree>8</degree>
		</spelling>
	</scale>

	<scale name="Bebop Dominant">
		<intervals>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>6</degree>
			<degree>b7</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Enigmatic">
		<intervals>
			<interval>1</interval>
			<interval>3</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b2</degree>
			<degree>3</degree>
			<degree>#4</degree>
			<degree>#5</degree>
			<degree>#6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Egyptian">
		<intervals>
			<interval>2</interval>
			<interval>3</interval>
			<interval>2</interval>
			<interval>3</interval>
			<interval>2</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Mohammedan">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Major Locrian">
		<intervals>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
			<interval>2</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>3</degree>
			<degree>4</degree>
			<degree>b5</degree>
			<degree>b6</degree>
			<degree>b7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Algerian">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>#4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Pelog2">
		<intervals>
			<interval>1</interval>
			<interval>2</interval>
			<interval>4</interval>
			<interval>3</interval>
			<interval>2</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b2</degree>
			<degree>b3</degree>
			<degree>5</degree>
			<degree>b7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Hindu">
		<intervals>
			<interval>2</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>b7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Spanish">
		<intervals>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>2</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>b2</degree>
			<degree>3</degree>
			<degree>4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>b7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Hungarian minor">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
			<interval>1</interval>
			<interval>3</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>#4</degree>
			<degree>5</degree>
			<degree>b6</degree>
			<degree>7</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Diminished minor">
		<intervals>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
			<interval>2</interval>
			<interval>1</interval>
		</intervals>
		<spelling>
			<degree>1</degree>
			<degree>2</degree>
			<degree>b3</degree>
			<degree>4</degree>
			<degree>b5</degree>
			<degree>b6</degree>
			<degree>bb7</degree>
			<degree>b8</degree>
			<degree>8</degree>
		</spelling>
	</scale>
	<scale name="Eight-tone Spanish">
		<intervals>
			<interval>1</interval>
			<interval>2</interval>
